app/cart/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import current_user
from ..models import Product, Cart

cart = Blueprint('cart', __name__, template_folder='cart_templates')

@cart.route('/my-cart')
def viewMyCart():
    products = Cart.query.order_by(Product.product_id).all()
    return render_template('my_cart.html', products=products)

@cart.route('/add/<int:product_id>')
def addToCart(product_id):
    product = Product.query.filter_by(product_id=product_id).first()
    product.saveToCart(current_user)
    product_name=product.title
    flash(f"{product_name} has been added!")
    return redirect(url_for('homePage'))

@cart.route('/remove/<int:product_id>')
def removeFromCart(product_id):
    product = Cart.query.filter_by(product_id=product_id).first()
    product.deleteFromCart(current_user)
    product_name=product.title
    flash(f"{product_name} has been Removed!")
    return redirect(url_for('homePage'))

@cart.route('/view-singe-item/<int:product_id>')
def viewSingleProduct(product_id):
    product = Product.query.get(product_id)
    return render_template('single_product.html',product=product)

@cart.route('/view-all-products')
def viewAllProducts():
    products = Product.query.order_by(Product.product_id).all()
    return render_template('all_products.html', products=products)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Purple</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="/app/static/main.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
  integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

  {% block css %}

  {% endblock %}
</head>

<body>

  {% include 'nav.html' %}

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
  
      {% for c, m in messages %}

    <div class="alert alert-{{ c }} alert-dismissible fade show text-warning fs-3 bg-success p-2 text-success bg-opacity-25" role="alert">
      <strong>{{ m }}</strong>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

      {% endfor %}
    {% endif %}
  {% endwith %}

  {% block content %}


  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
    integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">


  <body class="index">
    <h1>Welcome to Purple Crochet</h1>
   
    <h2>Shop cute and stylish Items!</h2>

  
 
  </body>



{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
  
      <a class="navbar-brand" href="{{ url_for('homePage') }}">Crochet</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('homePage') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About Us</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link">Welcome {{current_user.first_name}}!</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('cart.viewAllProducts') }}"><i class="fa-solid fa-tags"></i> Shop Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('cart.viewMyCart') }}"><i class="fa-solid fa-cart-shopping"></i> My Cart</a>
          </li>
          <a class="btn btn-outline-primary justify-content-end" href="#"
          role="button">DONT PRESS THIS BUTTON. ITS A FUNCITON TO ADD ITEMS TO DB</a>
          <a class="btn btn-outline-primary justify-content-end" href="{{ url_for('auth.logOut') }}"
            role="button">Logout</a>
        </ul>
  
        {%else%}
        <div class="justify-content-end">
          <a class="btn btn-outline-primary justify-content-end" href="{{ url_for('auth.loginPage') }}"
            role="button">Login</a>
          <a class="btn btn-outline-primary justify-content-end" href="{{ url_for('auth.registerPage') }}"
            role="button">Register</a>
        </div>
        {% endif %}
      </div>
  
    </div>
  </nav>